# Configurações do servidor
spring.application.name=rotina-service
server.port=8081

# Configurações do H2
spring.datasource.url=jdbc:h2:mem:rotinadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 (opcional - para visualizar banco)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.com.poc.servicemesh.rotinaservice=DEBUG
logging.level.org.springframework.web=INFOspring.application.name=rotina-service
